const gradientsPlugin = require('tailwindcss-plugins/gradients');
const plugin = require('tailwindcss/plugin');
const checTablesPlugin = require('./tailwind-plugins/tables');
const checTypeographyPlugin = require('./tailwind-plugins/typography');

const fontSizes = {
  xxs: '.625rem',
  xs: '.75rem',
  sm: '.938rem',
  base: '1rem',
  lg: '1.063rem',
  xl: '1.25rem',
  '2xl': '1.438rem',
  '3xl': '1.688rem',
  '4xl': '2rem',
  '5xl': '2.5rem',
};
module.exports = {
  purge: {
    enabled: true,
    content: [
      './components/**/*.vue',
      './components/*.vue',
      './components/*.js',
      './stories/**/*.mdx',
      './tailwind-plugins/**/*.js',
    ],
    options: {
      whitelist: [
        'mx-auto',
        'my-6',
        'my-2',
        'px-8',
        'px-16',
        'pt-4',
        'pt-6',
        'py-4',
        'py-6',
        'py-16',
        'pb-6',
        'mr-3',
        'm-40',
        'flex',
        'block',
        'text-left',
        'text-right',
        'text-center',
        'justify-center',
        'justify-between',
        'self-center',
        'items-center',
        'justify-around',
        'p-3',
        'p-4',
        'p-8',
        'p-16',
        'py-8',
        'mx-2',
        'mx-20',
        'bg-gray-100',
        'bg-gray-200',
        'bg-gray-400',
        'bg-white',
        'py-10',
        'w-1/2',
        'px-4',
        'max-w-xs',
        'max-w-sm',
        'max-w-md',
        'max-w-lg',
        'max-w-xl',
        'max-w-2xl',
        'max-w-3xl',
        'max-w-4xl',
        'max-w-5xl',
        'max-w-full',
        'max-w-6xl',
        'max-w-screen-sm',
        'max-w-screen-md',
        'max-w-screen-lg',
        'max-w-screen-xl',
        'max-w-screen-none',
        'flex-col',
        'my-2',
        'w-full',
        'font-bold',
        'text-red-200',
        'text-xs',
        'italic',
        'px-2',
        'mx-2',
        'mb-2',
        'mb-4',
        'mt-2',
        'mt-8',
        'w-4',
        'h-4',
        'w-6',
        'h-6',
        'w-12',
        'h-12',
        'w-24',
        'h-24',
        'w-40',
        'h-40',
        'w-48',
        'h-48',
        'rounded-sm',
        'rounded-md',
        'rounded-lg',
        'rounded-full',
        'space-y-4',
        'bg-primary-gradient',
        'text-white',
        'absolute',
        'w-32',
        'h-32,',
        'pointer-events-none',
        'invisible',
        'opacity-25',
        'bottom-0',
        'text-primary-blue',
        'text-gray-500',
        'text-blue-600',
        'text-green-600',
        'text-red-600',
        'text-purple-600',
        'text-orange-600',
        'grid',
        'grid-cols-4',
        'gap-4',
        'border-2',
        'border-black',
        'border',
        'border-gray-300',
        'primary-gradient',
        'gray-100',
        'gray-200',
        'gray-300',
        'gray-400',
        'gray-500',
        'gray-600',
        'dark-blue',
        'primary-blue',
        'hologram', 'primary-gradient-2',
        'gray-gradient',
      ],
    },
  },
  theme: {
    fontFamily: {
      lato: [
        'Lato',
        'sans-serif',
      ],
      mono: [
        'Roboto Mono',
        'monospace',
      ],
    },
    gradients: {
      'primary-gradient': ['33.69deg', '#254E81', '#2C7EA1'],
      'primary-gradient-2': ['85.06deg', '#254E81', '#2C7EA1'],
      'gray-gradient': ['180deg', '#F1F6FC', '#F8FAFD'],
      'vertical-transparent-gradient': ['0deg', 'rgba(255,255,255,0)', 'rgba(255,255,255,0.8)', 'rgba(255,255,255,1)'],
    },
    boxShadow: {
      default: '0px 0px 1px rgba(40, 51, 65, 0.2), 0px 1px 4px rgba(40, 51, 65, 0.1)',
      sm: '0px 0px 1px rgba(40, 51, 65, 0.2), 0px 1px 4px rgba(40, 51, 65, 0.1)',
      md: '0px 3px 12px rgba(40, 51, 65, 0.1), 0px 0px 1px rgba(40, 51, 65, 0.2)',
      lg: '0px 4px 16px rgba(40, 51, 65, 0.1), 0px 0px 1px rgba(40, 51, 65, 0.2)',
      inner: 'inset 0px 1px 2px rgba(40, 51, 65, 0.1)',
      none: 'none',
    },
    colors: {
      transparent: 'transparent',
      'dark-blue': '#254E81',
      'primary-blue': '#2C7EA1',
      'purple-600': '#6638AE',
      'purple-500': '#713EC1',
      'purple-400': '#8E65CD',
      'purple-300': '#AA8BDA',
      'purple-200': '#C6B2E6',
      'purple-100': '#EEE8F8',
      'red-600': '#C2243F',
      'red-500': '#D72846',
      'red-400': '#DF536B',
      'red-300': '#E77E90',
      'red-200': '#EFA9B5',
      'red-100': '#FAE5E9',
      'orange-600': '#DD6309',
      'orange-500': '#F56E0A',
      'orange-400': '#F78B3B',
      'orange-300': '#F9A86C',
      'orange-200': '#FBC59D',
      'orange-100': '#FEEEE1',
      'green-600': '#29A38A',
      'green-500': '#34CBAD',
      'green-400': '#5CD6BD',
      'green-300': '#85E0CE',
      'green-200': '#AEEADE',
      'green-100': '#EBFAF7',
      'blue-600': '#14ABD2',
      'blue-500': '#16BEE9',
      'blue-400': '#44CBEE',
      'blue-300': '#73D8F2',
      'blue-200': '#A1E5F7',
      'blue-100': '#E3F7FC',
      'gray-600': '#283341',
      'gray-500': '#41556C',
      'gray-400': '#7187A5',
      'gray-300': '#D3E0F1',
      'gray-200': '#F1F6FC',
      'gray-100': '#F8FAFD',
      white: '#FFFFFF',
      black: '#000000',
    },
    borderRadius: {
      none: '0',
      sm: '2px',
      default: '4px',
      md: '8px',
      lg: '12px',
      full: '9999px',
    },
    fontSize: fontSizes,
    letterSpacing: {
      tightest: '-.12em',
      tighter: '-.085em',
      tight: '-.025em',
      normal: '0',
      wide: '.025em',
      wider: '.085em',
      widest: '.12em',
    },
    borderWidth: {
      default: '1px',
      0: '0',
      2: '2px',
      4: '4px',
      8: '8px',
    },
    maxHeight: {
      0: '0',
      '1/4': '25%',
      '1/2': '50%',
      '3/4': '75%',
      full: '100%',
      'full-px': '9999px',
    },
    extend: {
      spacing: {
        ...fontSizes,
      },
      zIndex: {
        '-1': '-1',
      },
      opacity: {
        20: '0.2',
        40: '0.4',
      },
    },
  },
  variants: {
    gradients: ['responsive', 'hover'],
    transitionProperty: ['responsive', 'hover', 'focus'],
  },
  plugins: [
    checTablesPlugin,
    checTypeographyPlugin,
    gradientsPlugin,
    plugin(({ addUtilities }) => addUtilities({
      '.bg-hologram': {
        backgroundImage: 'inline("../assets/media/hologram-bg.png")',
      },
    })),
  ],
};
