name: Build library files and push changes

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.0.0
        name: Install
        with:
          cmd: install 
      - uses: borales/actions-yarn@v2.0.0
        name: Build
        with:
          cmd: build-lib
      - name: Commit
        id: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git diff --exit-code --quiet || (git commit -am "Build library bundles" && echo "::set-output name=status::built")
      - name: Push
        if: contains(steps.commit.outputs.status, 'built')
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
