name: Build library files and push changes

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.0.0
        name: Install
        with:
          cmd: install 
      - uses: borales/actions-yarn@v2.0.0
        name: Build
        with:
          cmd: build-lib
      - name: Check for changes
        run: git diff --exit-code --quiet
      - name: Commit
        if: failed()
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Build library bundles"
      - name: Push
        if: success()
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
